In [1]:
%load_ext Cython
from pycalphad.core.compiled_model import CompiledModel
from pycalphad import calculate, Database
from pycalphad.core.phase_rec import PhaseRecord
import pycalphad.variables as v
import numpy as np

In [2]:
dbf = Database('alcocr-sandbox.tdb')
res = calculate(dbf, ['AL', 'CO', 'VA'], 'BCC_B2', T=1000, P=101325, points=[[0.3, 0.6, 0.1, 0.6, 0.3, 0.1, 1]])
res.GM

<xarray.DataArray 'GM' (P: 1, T: 1, points: 1)>
array([[[-54538.94279231]]])
Coordinates:
  * P        (P) float64 1.013e+05
  * T        (T) float64 1e+03
  * points   (points) int64 0

In [3]:
cmpd = CompiledModel(dbf, ['AL', 'CO', 'VA'], 'BCC_B2')
from pycalphad.core.compiled_model import eval_energy
out = np.atleast_1d(np.zeros(1))
%time eval_energy(cmpd, out, np.array([101325, 1000, 0.3, 0.6, 0.1, 0.6, 0.3, 0.1, 1]), np.array([]), 1)
out

-7465.969729321696
-7465.969729321696
-8295.521921468551
('ordered_dof', array([  1.01325000e+05,   1.00000000e+03,   4.50000000e-01,
         4.50000000e-01,   1.00000000e-01,   4.50000000e-01,
         4.50000000e-01,   1.00000000e-01,   1.00000000e+00]))
('main_ord', -8295.5219214685512)
-7889.757391752295
-7889.757391752295
-8766.397101946994
('main-sub', 8766.3971019469936)
('disordered_energy', -54976.515447053105)
CPU times: user 17.3 ms, sys: 12 µs, total: 17.3 ms
Wall time: 16.3 ms


/home/rotis/anaconda/envs/calphadpy3/lib/python3.5/site-packages/ipykernel/__main__.py:1: RuntimeWarning: divide by zero encountered in double_scalars
  if __name__ == '__main__':


array([-54505.64026657])

In [4]:
dbf = Database('alcocr-sandbox.tdb')
res = calculate(dbf, ['AL', 'CO', 'VA'], 'BCC_A2', T=1000, P=101325, points=[[0.45, 0.45, 0.1, 1]])
res.GM

<xarray.DataArray 'GM' (P: 1, T: 1, points: 1)>
array([[[-55009.81797279]]])
Coordinates:
  * P        (P) float64 1.013e+05
  * T        (T) float64 1e+03
  * points   (points) int64 0

In [5]:
cmpd = CompiledModel(dbf, ['AL', 'CO', 'VA'], 'BCC_A2')
from pycalphad.core.compiled_model import eval_energy
out = np.atleast_1d(np.zeros(1))
%time eval_energy(cmpd, out, np.array([101325, 1000, 0.45, 0.45, 0.1, 1]), np.array([]), 1)
out

-42444.891402347814
-49478.86390234782
-55009.8154187113
CPU times: user 3.3 ms, sys: 13 µs, total: 3.31 ms
Wall time: 3.13 ms


array([-55009.81541871])