Current tasks
-------------
- Set _eval_energy and eval_energy to be nogil
- Make RedlichKisterSum a cdef class
- ~~Make CompiledModel a cdef class~~
- Link CompiledModel-based energy evaluation into the main solver
- Decide how/if to store gradients and Hessians of RedlichKisterSums
- Write analagous eval_gradient and eval_hessian functions
- Link gradient and Hessian for CompiledModel into main solver

In [1]:
from pycalphad.core.compiled_model import CompiledModel
from pycalphad import calculate, Database, Model
from pycalphad.core.phase_rec import PhaseRecord
import pycalphad.variables as v
import numpy as np

In [2]:
dbf = Database('alcocr-sandbox.tdb')

In [3]:
class ModelTest(Model):
    @property
    def mag_GM(self):
        return self.models['mag']
res = calculate(dbf, ['AL', 'CO', 'VA'], 'BCC_B2', T=1000, P=101325, points=[[0.3, 0.6, 0.1, 0.6, 0.3, 0.1, 1]], output='GM', model=ModelTest)
res.GM

<xarray.DataArray 'GM' (P: 1, T: 1, points: 1)>
array([[[-57590.99363009]]])
Coordinates:
  * T        (T) float64 1e+03
  * P        (P) float64 1.013e+05
  * points   (points) int64 0

In [7]:
cmpd = CompiledModel(dbf, ['AL', 'CO', 'VA'], 'BCC_B2')
from pycalphad.core.compiled_model import eval_energy
out = np.atleast_1d(np.zeros(1))
params = np.array([])
%time eval_energy(cmpd, out, np.array([101325, 1000, 0.3, 0.6, 0.1, 0.6, 0.3, 0.1, 1]), params, 1)
out

CPU times: user 0 ns, sys: 0 ns, total: 0 ns
Wall time: 166 µs


array([-57590.99363009])

In [5]:
dbf = Database('alcocr-sandbox.tdb')
res = calculate(dbf, ['AL', 'CO', 'VA'], 'BCC_A2', T=1000, P=101325, points=[[0.45, 0.45, 0.1, 1]])
res.GM

<xarray.DataArray 'GM' (P: 1, T: 1, points: 1)>
array([[[-55009.81541871]]])
Coordinates:
  * T        (T) float64 1e+03
  * P        (P) float64 1.013e+05
  * points   (points) int64 0

In [6]:
cmpd = CompiledModel(dbf, ['AL', 'CO', 'VA'], 'BCC_A2')
from pycalphad.core.compiled_model import eval_energy
out = np.atleast_1d(np.zeros(1))
%time eval_energy(cmpd, out, np.array([101325, 1000, 0.45, 0.45, 0.1, 1]), np.array([]), 1)
out

CPU times: user 0 ns, sys: 0 ns, total: 0 ns
Wall time: 54.1 µs


array([-55009.81541871])