In [1]:
import numpy as np
from pycalphad import Model, Database, calculate, equilibrium
from pycalphad.core.compiled_model import CompiledModel
import pycalphad.variables as v
from pycalphad.tests.datasets import ISSUE43_TDB
dbf = Database(ISSUE43_TDB)
models = {key: CompiledModel(dbf, ['AL', 'NI', 'CR', 'VA'], key, _debug=True) for key in dbf.phases.keys()}

In [2]:
eq = equilibrium(dbf, ['AL', 'NI', 'CR', 'VA'], ['FCC_A1', 'GAMMA_PRIME'],
                 {v.X('AL'): .1246, v.X('CR'): 0.6, v.T: 1273, v.P: 101325},
                 verbose=True, model=models)

Calculation Backend: Compiled (autowrap)
Components: AL CR NI VA
Phases: FCC_A1 GAMMA_PRIME [done]
--
Hessian mismatch

Not equal to tolerance rtol=1e-07, atol=0

(mismatch 76.5625%)
 x: array([[  0.000000e+00,   0.000000e+00,   0.000000e+00,   0.000000e+00,
          0.000000e+00,   0.000000e+00,   0.000000e+00,   0.000000e+00],
       [  0.000000e+00,  -2.817748e-02,  -7.978210e+01,  -5.906678e+01,...
 y: array([[  0.000000e+00,   0.000000e+00,   0.000000e+00,   0.000000e+00,
          0.000000e+00,   0.000000e+00,   0.000000e+00,   0.000000e+00],
       [  0.000000e+00,  -2.817743e-02,  -7.977725e+01,  -5.905774e+01,...
[[  0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00
    0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  0.00000000e+00   5.07798709e-08   4.84515785e-03   9.04381543e-03
    9.20275656e-04  -7.73102256e-03  -1.23256771e-02   4.57752251e-03]
 [  0.00000000e+00   4.84515785e-03   1.02541126e+01  -9.02733018e-02
   -2.92731301e+0

In [3]:
eq

<xarray.Dataset>
Dimensions:       (P: 1, T: 1, X_AL: 1, X_CR: 1, component: 3, internal_dof: 6, vertex: 3)
Coordinates:
  * P             (P) float64 1.013e+05
  * T             (T) float64 1.273e+03
  * X_AL          (X_AL) float64 0.1246
  * X_CR          (X_CR) float64 0.6
  * vertex        (vertex) int64 0 1 2
  * component     (component) <U2 'AL' 'CR' 'NI'
  * internal_dof  (internal_dof) int64 0 1 2 3 4 5
Data variables:
    X             (P, T, X_AL, X_CR, vertex, component) float64 0.05114 ...
    NP            (P, T, X_AL, X_CR, vertex) float64 0.00481 0.489 0.5062
    GM            (P, T, X_AL, X_CR) float64 -7.068e+04
    Phase         (P, T, X_AL, X_CR, vertex) <U11 'GAMMA_PRIME' ...
    MU            (P, T, X_AL, X_CR, component) float64 -1.356e+05 ...
    Y             (P, T, X_AL, X_CR, vertex, internal_dof) float64 0.02514 ...
Attributes:
    engine: pycalphad 0.4.2+166.g0f1534c.dirty
    solve_iterations: 17
    hull_iterations: 1
    created: 2017-03-21 16:43:47.350

In [4]:
eq.GM.values

array([[[[-70680.53700478]]]])

In [5]:
(eq.X * eq.NP).sum(axis=-2)

<xarray.DataArray (P: 1, T: 1, X_AL: 1, X_CR: 1, component: 3)>
array([[[[[ 0.1246,  0.6   ,  0.2754]]]]])
Coordinates:
  * P          (P) float64 1.013e+05
  * T          (T) float64 1.273e+03
  * X_AL       (X_AL) float64 0.1246
  * X_CR       (X_CR) float64 0.6
  * component  (component) <U2 'AL' 'CR' 'NI'

In [6]:
sum(np.squeeze(eq.MU.values) * [0.1246, 0.6, 1-(0.6+0.1246)])

-70680.536955136748

In [7]:
eq.Y

<xarray.DataArray 'Y' (P: 1, T: 1, X_AL: 1, X_CR: 1, vertex: 3, internal_dof: 6)>
array([[[[[[ 0.02514331,  0.79792414,  0.17693255,  0.12914576,
             0.86756816,  0.00328608],
           [ 0.02514334,  0.7979242 ,  0.17693246,  0.12914555,
             0.86756809,  0.00328636],
           [ 0.19624727,  0.38996739,  0.41378534,  1.        ,
                    nan,         nan]]]]]])
Coordinates:
  * P             (P) float64 1.013e+05
  * T             (T) float64 1.273e+03
  * X_AL          (X_AL) float64 0.1246
  * X_CR          (X_CR) float64 0.6
  * vertex        (vertex) int64 0 1 2
  * internal_dof  (internal_dof) int64 0 1 2 3 4 5

Hessian mismatch

Not equal to tolerance rtol=1e-07, atol=0

(mismatch 53.125%)
 x: array([[ -0.000000e+00,  -0.000000e+00,   0.000000e+00,   0.000000e+00,
          0.000000e+00,   0.000000e+00,   0.000000e+00,   0.000000e+00],
       [ -0.000000e+00,  -5.476986e-02,  -8.690206e+01,  -5.472656e+01,...
 y: array([[  0.000000e+00,  -6.635584e+01,  -1.515135e+05,   0.000000e+00,
         -2.664257e+05,   0.000000e+00,   0.000000e+00,   0.000000e+00],
       [  0.000000e+00,  -6.980498e+01,  -2.664257e+05,  -7.424881e+01,...
[[  0.00000000e+00  -6.63558420e+01  -1.51513479e+05   0.00000000e+00
   -2.66425667e+05   0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  0.00000000e+00  -6.97502143e+01  -2.66338765e+05  -1.95222520e+01
   -1.02480385e+05   1.25225654e+02   0.00000000e+00   0.00000000e+00]
 [  0.00000000e+00   1.26532444e+01  -7.03144582e+04  -1.22393038e+05
   -4.33049259e+04   2.66505973e+05   0.00000000e+00   0.00000000e+00]
 [  0.00000000e+00  -8.49995534e+01   2.90506364e+04  -3.67187926e+04
   -2.68563738e+05   1.02556891e+05   0.00000000e+00   0.00000000e+00]
 [  0.00000000e+00   7.53462656e+01   1.22406719e+05   2.21757348e+04
   -1.97110052e+04   1.94854455e+05   0.00000000e+00   0.00000000e+00]
 [  0.00000000e+00   5.88698116e+01   3.00750789e+05  -9.22638253e+04
    1.94854455e+05   3.52309661e+05   0.00000000e+00   0.00000000e+00]
 [  0.00000000e+00   7.03350099e+04  -2.48465473e+03   0.00000000e+00
    0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [ -2.72785265e-02  -2.91090718e+04  -1.02555731e+05  -1.39726116e+02
    0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00]]
('DOF:', array([  1.01325000e+05,   1.27300000e+03,   1.91466366e-01,
         4.29294845e-01,   3.79238789e-01,   1.00000000e+00]))
[['AL', 'CR', 'NI'], ['VA']]

In [8]:
mod = Model(dbf, ['AL', 'CR', 'NI', 'VA'], 'FCC_A1')
mod.GM.diff(v.T, v.P)

0