In [1]:
import numpy as np
from pycalphad import Model, Database, calculate, equilibrium
from pycalphad.core.compiled_model import CompiledModel
import pycalphad.variables as v
from pycalphad.tests.datasets import ISSUE43_TDB
dbf = Database(ISSUE43_TDB)
models = {key: CompiledModel(dbf, ['AL', 'NI', 'CR', 'VA'], key, _debug=True) for key in dbf.phases.keys()}

In [2]:
eq = equilibrium(dbf, ['AL', 'NI', 'CR', 'VA'], ['FCC_A1', 'GAMMA_PRIME'],
                 {v.X('AL'): .1246, v.X('CR'): 0.6, v.T: 1273, v.P: 101325},
                 verbose=True, model=models)

Calculation Backend: Compiled (autowrap)
Components: AL CR NI VA
Phases: FCC_A1 GAMMA_PRIME [done]
--
Hessian mismatch

Not equal to tolerance rtol=1e-07, atol=0

(mismatch 76.5625%)
 x: array([[ -0.000000e+00,  -0.000000e+00,   0.000000e+00,   0.000000e+00,
          0.000000e+00,   0.000000e+00,   0.000000e+00,   0.000000e+00],
       [ -0.000000e+00,  -5.137644e-02,  -8.289674e+01,  -4.568301e+01,...
 y: array([[  0.000000e+00,   0.000000e+00,   0.000000e+00,   0.000000e+00,
          0.000000e+00,   0.000000e+00,   0.000000e+00,   0.000000e+00],
       [  0.000000e+00,  -2.817743e-02,  -7.977725e+01,  -5.905774e+01,...
[[  0.           0.           0.           0.           0.           0.
    0.           0.        ]
 [  0.           0.02319901   3.11948884 -13.37472691  -8.71969927
   -7.03431781 -13.26053468 -17.5185376 ]
 [  0.           3.11948884  10.25411258  -0.0902733   -2.92731301
   -0.61794984  -6.85066577  15.4538729 ]
 [  0.         -13.37472691  -0.0902733   -2.52434

In [3]:
eq

<xarray.Dataset>
Dimensions:       (P: 1, T: 1, X_AL: 1, X_CR: 1, component: 3, internal_dof: 6, vertex: 3)
Coordinates:
  * P             (P) float64 1.013e+05
  * T             (T) float64 1.273e+03
  * X_AL          (X_AL) float64 0.1246
  * X_CR          (X_CR) float64 0.6
  * vertex        (vertex) int64 0 1 2
  * component     (component) <U2 'AL' 'CR' 'NI'
  * internal_dof  (internal_dof) int64 0 1 2 3 4 5
Data variables:
    NP            (P, T, X_AL, X_CR, vertex) float64 1.0 nan nan
    GM            (P, T, X_AL, X_CR) float64 -7.057e+04
    MU            (P, T, X_AL, X_CR, component) float64 -1.354e+05 ...
    Phase         (P, T, X_AL, X_CR, vertex) <U11 'FCC_A1' '' ''
    X             (P, T, X_AL, X_CR, vertex, component) float64 0.1246 0.6 ...
    Y             (P, T, X_AL, X_CR, vertex, internal_dof) float64 0.1246 ...
Attributes:
    hull_iterations: 1
    engine: pycalphad 0.4.2+165.g785d3d6.dirty
    solve_iterations: 7
    created: 2017-03-20 23:49:40.127052

In [4]:
eq.GM.values

array([[[[-70567.73287848]]]])

In [5]:
(eq.X * eq.NP).sum(axis=-2)

<xarray.DataArray (P: 1, T: 1, X_AL: 1, X_CR: 1, component: 3)>
array([[[[[ 0.1246,  0.6   ,  0.2754]]]]])
Coordinates:
  * P          (P) float64 1.013e+05
  * T          (T) float64 1.273e+03
  * X_AL       (X_AL) float64 0.1246
  * X_CR       (X_CR) float64 0.6
  * component  (component) <U2 'AL' 'CR' 'NI'

In [6]:
sum(np.squeeze(eq.MU.values) * [0.1246, 0.6, 1-(0.6+0.1246)])

-70567.732878482057

In [7]:
eq.Y

<xarray.DataArray 'Y' (P: 1, T: 1, X_AL: 1, X_CR: 1, vertex: 3, internal_dof: 6)>
array([[[[[[ 0.1246,  0.6   ,  0.2754,  1.    ,     nan,     nan],
           [    nan,     nan,     nan,     nan,     nan,     nan],
           [    nan,     nan,     nan,     nan,     nan,     nan]]]]]])
Coordinates:
  * P             (P) float64 1.013e+05
  * T             (T) float64 1.273e+03
  * X_AL          (X_AL) float64 0.1246
  * X_CR          (X_CR) float64 0.6
  * vertex        (vertex) int64 0 1 2
  * internal_dof  (internal_dof) int64 0 1 2 3 4 5