In [1]:
import matplotlib.pyplot as plt
from pycalphad import equilibrium
from pycalphad import Database, Model
import pycalphad.variables as v
import numpy as np

db = Database()
db.elements = frozenset({'A', 'B', 'C'})
db.add_phase('TEST', {}, [1])
db.add_phase_constituents('TEST', [['A', 'B', 'C']])
my_phases = ['TEST']

eq = equilibrium(db, ['A', 'B', 'C'], my_phases,
                 {v.X('A'): .2, v.X('B'): .2, v.T: 1273, v.P: 101325}, calc_opts={'pdens': 100},
                 verbose=True, pbar=False)
print(eq)

Calculation Backend: Interpreted (autograd)
Components: A B C
Phases: Phase({'model_hints': {}, 'sublattices': (1,), 'constituents': (frozenset({'A', 'B', 'C'}),), 'name': 'TEST'}) A
Y(TEST,0,A)
Phase({'model_hints': {}, 'sublattices': (1,), 'constituents': (frozenset({'A', 'B', 'C'}),), 'name': 'TEST'}) B
Y(TEST,0,B)
Phase({'model_hints': {}, 'sublattices': (1,), 'constituents': (frozenset({'A', 'B', 'C'}),), 'name': 'TEST'}) C
Y(TEST,0,C)
TEST [done]
Computing initial grid [506 points, 44.6KB]
Computing convex hull [iteration 1]
progress 15790.6579866 [0 conditions updated]
Global search complete
Refining equilibrium
INITIAL CONFIGURATION
<xarray.DataArray 'MU' (P: 1, T: 1, X_A: 1, X_B: 1, component: 3)>
array([[[[[-15790.65798661, -15449.20256191,  -6264.80667561]]]]])
Coordinates:
  * P          (P) float64 1.013e+05
  * T          (T) float64 1.273e+03
  * X_A        (X_A) float64 0.2
  * X_B        (X_B) float64 0.2
  * component  (component) object 'A' 'B' 'C'
<xarray.DataArray 

/home/rotis/anaconda/envs/calphadpy3/lib/python3.5/site-packages/autograd-1.1.2-py3.5-linux-x86_64.egg/autograd/core.py:68: UserWarning: Output seems independent of input. Returning zero gradient.


In [2]:
8.3145*1273*(0.2*np.log(0.2)+0.2*np.log(0.2)+0.6*np.log(0.6))

-10058.004059232871

In [3]:
8.3145*1273*(np.log(0.6))

-5406.7615329253658

In [4]:
eq.MU

<xarray.DataArray 'MU' (P: 1, T: 1, X_A: 1, X_B: 1, component: 3)>
array([[[[[-17034.86784869, -17034.86784869,  -5406.76153293]]]]])
Coordinates:
  * P          (P) float64 1.013e+05
  * T          (T) float64 1.273e+03
  * X_A        (X_A) float64 0.2
  * X_B        (X_B) float64 0.2
  * component  (component) object 'A' 'B' 'C'

In [5]:
total_comp = np.nansum(eq.NP.values[..., np.newaxis] * eq.X.values, axis=-2)
print(total_comp)
print((eq.MU * total_comp).sum(axis=-1) - eq.GM)

[[[[[ 0.2  0.2  0.6]]]]]
<xarray.DataArray (P: 1, T: 1, X_A: 1, X_B: 1)>
array([[[[ -1.81898940e-12]]]])
Coordinates:
  * P        (P) float64 1.013e+05
  * T        (T) float64 1.273e+03
  * X_A      (X_A) float64 0.2
  * X_B      (X_B) float64 0.2
